###############################
#Github Actions to verify feature flags
###############################
name: Verify-Featureflags

#controls when the pipeline will trigger
on:
  pull_request:
    branches:
      - main

jobs:

  ####################################
  # verify feature flags script. Runs only on PR when targeted branch is main
  ####################################
  verify-featureflags:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/

    strategy:
      matrix:
        python-version: [3.8]

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ENV1: ${{ vars.ENV1 }}
      ENV2: ${{ vars.ENV2 }}
      URL: ${{ vars.URL }}
      PROJECT_KEY: ${{ vars.PROJECT_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Verify feature flags
        run: |
          python ./verify_featureflags.py
